# Generated by Django 6.0.1 on 2026-02-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='is_avaliable',
        ),
        migrations.AddField(
            model_name='cloth',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cloth',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cloth',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloth',
            name='title',
            field=models.CharField(default='Clothing Item', max_length=100),
        ),
        migrations.AddField(
            model_name='clothbrand',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
