# Generated by Django 6.0.1 on 2026-02-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_shop', '0002_remove_cloth_is_avaliable_cloth_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='category',
            field=models.CharField(choices=[('SHOES', 'Shoes'), ('T-SHIRTS', 'T-shirts'), ('PANTS', 'Pants'), ('SOCKS', 'Socks'), ('UNDERWEAR', 'Underwear'), ('HATS', 'Hats')], default='T-SHIRTS', max_length=20),
        ),
    ]
